/**
 * Auth actions
 */
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const LOGOUT_USER = 'LOGOUT_USER';

/**
 * Message actions
 */
 export const GET_CHAT_LIST_LOADING = 'GET_CHAT_LIST_LOADING';
 export const GET_CHAT_LIST_SUCCESS = 'GET_CHAT_LIST_SUCCESS';
 export const GET_CHAT_LIST_FAIL = 'GET_CHAT_LIST_FAIL';

 export const GET_CONTENT_MESS_LOADING = 'GET_CONTENT_MESS_LOADING';
 export const GET_CONTENT_MESS_SUCCESS = 'GET_CONTENT_MESS_SUCCESS';
 export const GET_CONTENT_MESS_FAIL = 'GET_CONTENT_MESS_FAIL';

/**
 * Contact actions
 */
export const GET_LIST_CONTACTS_LOADING = 'GET_LIST_CONTACTS_LOADING';
export const GET_LIST_CONTACTS_SUCCESS = 'GET_LIST_CONTACTS_SUCCESS';
export const GET_LIST_CONTACTS_FAIL = 'GET_LIST_CONTACTS_FAIL';

export const GET_FRIEND_REQUESTS_LOADING = 'GET_FRIEND_REQUESTS_LOADING';
export const GET_FRIEND_REQUESTS_SUCCESS = 'GET_FRIEND_REQUESTS_SUCCESS';
export const GET_FRIEND_REQUESTS_FAIL = 'GET_FRIEND_REQUESTS_FAIL';

export const SET_ACCEPT_REQUEST_LOADING = 'SET_ACCEPT_REQUEST_LOADING';
export const SET_ACCEPT_REQUEST_SUCCESS = 'SET_ACCEPT_REQUEST_SUCCESS';
export const SET_ACCEPT_REQUEST_FAIL = 'SET_ACCEPT_REQUEST_FAIL';

export const ADD_FRIEND_BY_ID_LOADING = 'ADD_FRIEND_BY_ID_LOADING';
export const ADD_FRIEND_BY_ID_SUCCESS = 'ADD_FRIEND_BY_ID_SUCCESS';
export const ADD_FRIEND_BY_ID_FAIL = 'ADD_FRIEND_BY_ID_FAIL';
export const CLEAR_ADD_FRIEND_BY_ID_STATE = 'CLEAR_ADD_FRIEND_BY_ID_STATE';

export const GET_CONTACT_BY_PHONE_LOADING = 'GET_CONTACT_BY_PHONE_LOADING';
export const GET_CONTACT_BY_PHONE_SUCCESS = 'GET_CONTACT_BY_PHONE_SUCCESS';
export const GET_CONTACT_BY_PHONE_FAIL = 'GET_CONTACT_BY_PHONE_FAIL';
export const CLEAR_GET_CONTACT_BY_PHONE_STATE = 'CLEAR_GET_CONTACT_BY_PHONE_STATE';

/**
 * Post actions
 */
 export const GET_LIST_POST_LOADING = 'GET_LIST_POST_LOADING';
 export const GET_LIST_POST_SUCCESS = 'GET_LIST_POST_SUCCESS';
 export const GET_LIST_POST_FAIL = 'GET_LIST_POST_FAIL';

/**
 * Channel actions
 */

